# Generated by Django 5.0.2 on 2024-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='performed',
            field=models.BooleanField(default=False),
        ),
    ]
