# Generated by Django 5.0.2 on 2024-03-19 07:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=255, populate_from='name', unique=True, verbose_name='الاسم المختصر'),
            preserve_default=False,
        ),
    ]
